language: ruby
bundler_args: "--without development --path=~/.bundle"
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler bundle_cache
- bundle_cache_install
rvm:
- 2.1.2
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database tayda_inventory_test;'
- bundle exec rake db:create db:migrate db:schema:load
after_script:
- bundle_cache
env:
  global:
  - BUNDLE_ARCHIVE="project-bundle"
  - AWS_S3_BUCKET="travisci-bundler-cache"
  - RAILS_ENV=test
 
